import Head from 'next/head'
import BenefitsSection from '../components/BenefitsSection'
import Contact from '../components/Contact'
import MainSection from '../components/MainSection'
import Navbar from '../components/Navbar'
import Comments from '../components/Comments'
import Footer from '../components/Footer'
import styles from '../styles/Home.module.css'

export default function Home() {
   return (
      <div className={styles.container}>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com"></link>
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
            <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet"></link>
            <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"></link>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossOrigin="anonymous" referrerpolicy="no-referrer" />
         </Head>

         <Navbar />
         <MainSection />
         <BenefitsSection />

         <section className={styles.contact_section}>
            <Contact />
         </section>

         <section className={styles.comments_section}>
            <Comments />
            <Comments />
         </section>

         <Footer />
         

      </div>
   )
}
